# Generated by Django 2.2 on 2019-05-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_student_attend'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registered',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
    ]
