# Generated by Django 2.2 on 2019-05-04 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20190504_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Counselor',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.Counselor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='School',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.School'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('first_name', 'last_name', 'School', 'Counselor')},
        ),
    ]
