# Generated by Django 2.2 on 2019-05-04 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190504_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='School',
            field=models.OneToOneField(help_text='Select your school', on_delete=django.db.models.deletion.CASCADE, to='catalog.School'),
        ),
    ]
